on:
  push:
    branches:
      - main
name: 🚀 Deploy
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER_CPANEL }}
          username: ${{ secrets.FTP_USER_CPANEL }}
          password: ${{ secrets.FTP_PASS_CPANEL }}
